name: 🚀 Release
on:
  push:
    tags:
      - '*'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    environment:
      name: test-github-pages
      url: ${{ steps.deployment.outputs.page_url }} 
    name: prod-release-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      ############################################
      # Install Java
      ###########################################    
            
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      ############################################
      # Setting up the xwiki repo (in a maven centraml publication compatible way)
      ###########################################   
      - uses: s4u/maven-settings-action@v3.1.0
        with:
          repositories: '[{"id":"xwiki-releases","name":"xwiki-releases","url":"https://maven.xwiki.org/releases/","snapshots":{"enabled":false}}]'

      ############################################
      # Build jars + maven site
      ###########################################   
                                
      - name: Build  Maven site
        working-directory: ./xwiki-spring-boot-starter   
        run: mvn --batch-mode clean install
                                              
     ############################################
      # Create the release with changelog,
      # PR Oriented
      ###########################################    
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        with:
          fetchReleaseInformation: true
          outputFile: PR-CHANGELOG.txt
          configurationJson: |
            {
              "template": "## 🥳 Welcome to this new version !\nWe hope you will appreciate the following improvements, this release <b>covers #{{DAYS_SINCE}} day</b> (or night) of work, starting the #{{FROM_TAG_DATE}} and ending at #{{TO_TAG_DATE}}. You may want to see the <b>#{{TO_TAG}}</b> release in action here : <ul><li><a target='_blank' href='https://nudger.fr'>nudger.fr</a></li><li><a target='_blank' href='https://open4good.github.io/open4goods/'>documentation</a></li></ul>\n### File changes\n<ul><li><a href='#{{RELEASE_DIFF}}'>Changed files</a>  : <b>#{{CHANGED_FILES}}</b> </li><li>Commits : <b>#{{COMMITS}}</b> </li><li>Additions : <b>#{{ADDITIONS}}</b></li><li>Deletions : <b>#{{DELETIONS}}</b></li> </ul>\n\n## Included Pull Requests\n#{{CHANGELOG}}\n\n### ❓ Other (#{{UNCATEGORIZED_COUNT}})\n\n#{{UNCATEGORIZED}}",
              "pr_template": "##{{NUMBER}} - #{{TITLE}} (#{{AUTHOR}})",            
              "empty_template": "Nothing",
              
              "categories": [
                 {
                    "title": "### 💡 Features",
                    "labels": ["feature"]
                },
                {
                    "title": "### 🔥 Bug Fixes",
                    "labels": ["bug"]
                },
                {
                    "title": "### ⚡ Performance",
                    "labels": ["performance"]
                },                
                {
                    "title": "### 💬 Documentation",
                    "labels": ["documentation"]
                },
                {
                    "title": "### 📦 Dependencies",
                    "labels": ["dependencies"]
                }
              ]
            }     


      ############################################
      # Create the release with changelog,
      # push Oriented
      ###########################################    

      - name: "Build Changelog push oriented"
        id: build_changelog_push
        uses: mikepenz/release-changelog-builder-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
        with:
         fetchReleaseInformation: true
         outputFile: PUSH-CHANGELOG.txt
         commitMode: true
         configurationJson: |
            {
              "template": "## 🙈 Direct commits\n#{{UNCATEGORIZED}}",
              "pr_template": "#{{TITLE}} (#{{AUTHOR}})",
             
              "empty_template": "Nothing",
              
              "categories": []
            }     

      ############################################
      # Merge the backlogs
      ###########################################    

      - name: Merge site
        run: cat PUSH-CHANGELOG.txt >> PR-CHANGELOG.txt          
    

            

          
      ############################################
      # Github pages deployment 
      ###########################################   
        
 #     - name: Setup github Pages
 #       uses: actions/configure-pages@v4    

#      - name: Merge site
#        working-directory: ./xwiki-spring-boot-starter      
#        run: cp -r target/staging/* src/main/site/maven/
                        
          
 #     - name: Upload pen4goods custom site
 #       uses: actions/upload-pages-artifact@v3
 #       with:	
 #         path: './src/main/site/'

 #     - name: Deploy to GitHub Pages
 #       id: deployment
 #       uses: actions/deploy-pages@v4
        
      ############################################
      # Maven central jar publication 
      ###########################################           
        
        
      - name: Publish package
        working-directory: ./xwiki-spring-boot-starter  
        env:
          MAVEN_USERNAME: ${{ secrets.JRELEASER_NEXUS2_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.JRELEASER_NEXUS2_PASSWORD }}
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.JRELEASER_NEXUS2_USERNAME }}
          JRELEASER_NEXUS2_PASSWORD: ${{ secrets.JRELEASER_NEXUS2_PASSWORD }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn deploy jreleaser:deploy -DaltDeploymentRepository=local::file:./target/staging-deploy        
        
      # Persist logs

      - name: JReleaser release output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jreleaser-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties   
        
        